export const SAVE_DATA_FULLFILLED = 'SAVE_DATA_FULLFILLED';
export const SAVE_DATA_LOADING = 'SAVE_DATA_LOADING';
export const SAVE_DATA_REJECTED = 'SAVE_DATA_REJECTED';

//add product
export const ADD_PRODUCT_FULLFILLED = 'ADD_PRODUCT_FULLFILLED';
export const ADD_PRODUCT_LOADING = 'ADD_PRODUCT_LOADING';
export const ADD_PRODUCT_REJECTED = 'ADD_PRODUCT_REJECTED';



export const DELETE_DATA = 'DELETE_DATA';